#!/bin/bash

#############################################################
# File Name   : report.sh
# Description : Generates Server Monitoring Reports
# Author      : Your Name
#############################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

REPORT_DIR="$SCRIPT_DIR/reports"

TEXT_REPORT="$REPORT_DIR/server-report.txt"
HTML_REPORT="$REPORT_DIR/server-report.html"

mkdir -p "$REPORT_DIR"

DATE=$(date "+%Y-%m-%d %H:%M:%S")
HOST=$(hostname)

#############################################
# Generate Text Report
#############################################

generate_text_report() {

echo "Generating Text Report..."

cat <<EOF > "$TEXT_REPORT"

==========================================================
            SERVER PERFORMANCE REPORT
==========================================================

Generated Time : $DATE
Hostname       : $HOST

==========================================================

EOF

modules=(
cpu.sh
memory.sh
disk.sh
network.sh
docker.sh
kubernetes.sh
security.sh
filesystem.sh
health-check.sh
)

for module in "${modules[@]}"
do
    if [ -f "$SCRIPT_DIR/$module" ]; then
        echo "" >> "$TEXT_REPORT"
        echo "==================================================" >> "$TEXT_REPORT"
        echo "Module : $module" >> "$TEXT_REPORT"
        echo "==================================================" >> "$TEXT_REPORT"

        bash "$SCRIPT_DIR/$module" >> "$TEXT_REPORT" 2>/dev/null

        echo "" >> "$TEXT_REPORT"

    else
        echo "$module not found." >> "$TEXT_REPORT"
    fi
done

echo "Text report saved:"
echo "$TEXT_REPORT"

}

#############################################
# Generate HTML Report
#############################################

generate_html_report() {

echo "Generating HTML Report..."

cat <<EOF > "$HTML_REPORT"

<!DOCTYPE html>
<html>
<head>

<title>Server Performance Report</title>

<style>

body{

font-family:Arial;
background:#f4f4f4;
margin:30px;

}

.container{

background:white;
padding:20px;
border-radius:10px;
box-shadow:0px 0px 10px gray;

}

h1{

color:#1E88E5;

}

h2{

background:#1E88E5;
color:white;
padding:10px;

}

pre{

background:#eeeeee;
padding:10px;
overflow:auto;

}

.footer{

text-align:center;
margin-top:40px;
color:gray;

}

</style>

</head>

<body>

<div class="container">

<h1>Server Performance Report</h1>

<p><b>Generated :</b> $DATE</p>
<p><b>Hostname :</b> $HOST</p>

EOF

modules=(
cpu.sh
memory.sh
disk.sh
network.sh
docker.sh
kubernetes.sh
security.sh
filesystem.sh
health-check.sh
)

for module in "${modules[@]}"
do

echo "<h2>$module</h2>" >> "$HTML_REPORT"

echo "<pre>" >> "$HTML_REPORT"

if [ -f "$SCRIPT_DIR/$module" ]; then

bash "$SCRIPT_DIR/$module" >> "$HTML_REPORT" 2>/dev/null

else

echo "$module not found." >> "$HTML_REPORT"

fi

echo "</pre>" >> "$HTML_REPORT"

done

cat <<EOF >> "$HTML_REPORT"

<div class="footer">

Generated by Server Performance Monitor

</div>

</div>

</body>

</html>

EOF

echo "HTML report saved:"
echo "$HTML_REPORT"

}

#############################################
# Main Menu
#############################################

case "$1" in

text)

generate_text_report
;;

html)

generate_html_report
;;

all)

generate_text_report
generate_html_report
;;

*)

echo ""
echo "Usage:"
echo "--------------------------------------------"
echo "./report.sh text"
echo "./report.sh html"
echo "./report.sh all"
echo "--------------------------------------------"
;;

esac
